from marshmallow import Schema, fields, validate

class UserSchema(Schema):
    #dump_only means that the id field cannot be provided by the user, it is generated by the backend
    id = fields.Int(dump_only=True)
    
    username = fields.Str(
        required=True,
        error_messages={"required": "Username is required"}
    )

    role = fields.Str(
        required=True,
        validate=validate.OneOf(["admin", "staff", "user"]),
        error_messages={"required": "Role is required"}
    )